---
version:                      "3.8"

services:

  web:
    image:                    github-demo:latest
    ports:
      - 80:80
    healthcheck:
      test:                   [ "CMD", "curl", "-f", "http://127.0.0.1:80/" ]
      interval:               5s
      timeout:                10s
      retries:                10
    restart:                  unless-stopped
