name: Docker Image CI

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    # - uses: einaregilsson/build-number@v1
    #   with:
    #     token: ${{secrets.github_token}}

    # - name: Output BUILD_NUMBER
    #   run: echo $BUILD_NUMBER
    - name:  Output Run ID
      shell: bash
      env:
        DEMO_SECRET: ${{ secrets.demo_secret }}
      run:   |
        echo "DEMO_SECRET is $DEMO_SECRET"
        echo "demo_secret is ${{ secrets.demo_secret }}"
        echo "Run ID      is ${{ github.run_id }}"
        echo "Run Number  is ${{ github.run_number }}"

    # - name: Output Run ID
    #   run:  echo ${{ github.run_id }}

    # - name: Output Run Number
    #   run:  echo ${{ github.run_number }}

    # - name: Build Docker image
    #   run:  docker build -t aaheiev/github-demo:latest .

    # - name: Tag Docker image
    #   run:  docker tag aaheiev/github-demo:latest aaheiev/github-demo:${{ github.run_number }}

    # - name: Tag Docker image
    #   run:  docker build -t aaheiev/github-demo:latest .

      # run: docker build . --file Dockerfile --tag aaheiev/github-demo:latest:$(date +%s)
