name: Docker Image CI

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name:  Output Variables
      shell: bash
      env:
        DEMO_SECRET: ${{ secrets.demo_secret }}
      run:   |
        echo "DEMO_SECRET is $DEMO_SECRET"
        echo "demo_secret is ${{ secrets.demo_secret }}"
        echo "Run ID      is ${{ github.run_id }}"
        echo "Run Number  is ${{ github.run_number }}"

    - name:  Build Docker image
      run:   docker build -t aaheiev/github-demo:latest .

  test:
    runs-on: ubuntu-latest
    needs:   build
    steps:

    - uses:  actions/checkout@v2

    - name:  Output Variables
      shell: bash
      env:
        DEMO_SECRET: ${{ secrets.demo_secret }}
      run:   |
        echo "DEMO_SECRET is $DEMO_SECRET"
        echo "demo_secret is ${{ secrets.demo_secret }}"
        echo "Run ID      is ${{ github.run_id }}"
        echo "Run Number  is ${{ github.run_number }}"

    # - name: Tag Docker image
    #   run:  docker tag aaheiev/github-demo:latest aaheiev/github-demo:${{ github.run_number }}

    # - name: Tag Docker image
    #   run:  docker build -t aaheiev/github-demo:latest .

      # run: docker build . --file Dockerfile --tag aaheiev/github-demo:latest:$(date +%s)

  publish:
    runs-on: ubuntu-latest
    needs:   test
    steps:

    - uses: actions/checkout@v2

    - name:  Output Variables
      shell: bash
      env:
        DEMO_SECRET: ${{ secrets.demo_secret }}
      run:   |
        echo "DEMO_SECRET is $DEMO_SECRET"
        echo "demo_secret is ${{ secrets.demo_secret }}"
        echo "Run ID      is ${{ github.run_id }}"
        echo "Run Number  is ${{ github.run_number }}"

    # - name: Tag Docker image
    #   run:  docker tag aaheiev/github-demo:latest aaheiev/github-demo:${{ github.run_number }}

    # - name: Tag Docker image
    #   run:  docker build -t aaheiev/github-demo:latest .

      # run: docker build . --file Dockerfile --tag aaheiev/github-demo:latest:$(date +%s)
